---
title: "VAST Challenge 2021 MC2" 
description: |
  User performance analytics based on movement and purchase data.
author:
  - name: Youzhen Zhang
    url: https://example.com/norajones
date: 07-14-2021
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 3
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# 1. Backgroud

### 1.1 Introduction of Case

Several employees of GAStech go missing, the case is under investigation.

Many of the Abila, Kronos-based employees of GAStech have company cars which were installed geospatial tracking software to track data periodically as long as they are moving.

This vehicle tracking data has been made available to law enforcement to support their investigation. Unfortunately, data is not available for the day the GAStech employees went missing. Data is only available for the two weeks prior to the disappearance.

Also, Kronos based companies provide a Kronos Kares benefit card to GASTech employees giving them discounts and rewards in exchange for collecting information about their credit card purchases and preferences as recorded on loyalty cards. This data has been made available to investigators in the hopes that it can help resolve the situation.


### 1.2 Requirements

The task in this case is to identify which GASTech employees made which purchases and identify suspicious patterns of behavior. 

1. Using just the credit and loyalty card data, identify the most popular locations, and when they are popular. Also, recommendations should be given to correct these anomalies.

2. Add the vehicle data to analysis of the credit and loyalty card data and figure out the discrepancies between vehicle, credit, and loyalty card data.

3. Infer the owners of each credit card and loyalty card and provide the evidences for that.

# 2. 



